# Change these first
owner: uniquebotsproject # Your GitHub organization or username
repo: status-page # Your GitHub repository name

# Add your sites here
sites:
  - name: UNIQUEBOTS
    url: https://uniquebots.kr

status-website:
  cname: status.uniquebots.kr
  logoUrl: https://cdn.discordapp.com/avatars/785407404031868949/56cdb6f7453572f7a72f7e047b9cb8e9.png?size=4096
  name: UNIQUEBOTS
  introTitle: UNIQUEBOTS, 디스코드 봇 리스트
  navbar:
    - title: Status
      href: /
assignees: # Users to assign downtime issues (optional)
  - pikokr


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
